import type { ReactNode } from "react";
import Link from "next/link";
import { ArrowRight, BrainCircuit, ChevronRight, CircleAlert, FileText, LayoutDashboard, LogOut, Menu, Plus, School, Sparkles, Users } from "lucide-react";

export function Logo({ compact = false }: { compact?: boolean }) {
  return <div className="flex items-center gap-3"><div className="grid h-10 w-10 place-items-center rounded-xl bg-[var(--primary)] text-white shadow-[0_8px_20px_rgba(36,87,214,.18)]"><BrainCircuit size={20} strokeWidth={2.2}/></div>{!compact && <div><p className="text-[13px] font-semibold leading-none tracking-tight">Smart Assessment</p><p className="mt-1 text-[11px] text-[var(--muted)]">Learn what matters</p></div>}</div>;
}

const nav = {
  teacher: [["Dashboard","/dashboard",LayoutDashboard],["Classes","/classes",Users],["Assessments","/assessments",FileText]],
  student: [["Dashboard","/student",LayoutDashboard],["My Classes","/join",School],["Learning Gaps","/gaps",CircleAlert]],
  principal: [["Overview","/principal",LayoutDashboard],["Classes","/principal/classes",School],["Teachers","/principal/teachers",Users],["Assessments","/principal/assessments",FileText]],
} as const;

export function AppShell({ role, active, children }: { role: keyof typeof nav; active: string; children: ReactNode }) {
  const items = nav[role];
  return <div className="min-h-screen bg-[var(--background)]"><aside className="fixed inset-y-0 left-0 z-40 hidden w-[248px] border-r border-[var(--border)] bg-white px-4 py-5 lg:block"><div className="px-3"><Logo/></div><div className="mt-9 px-3 text-[10px] font-semibold uppercase tracking-[.16em] text-[var(--muted-foreground)]">Workspace</div><nav className="mt-3 space-y-1">{items.map(([label,href,Icon])=><Link key={label} href={href} className={`flex items-center gap-3 rounded-xl px-3 py-2.5 text-sm transition ${active===label?"bg-[var(--primary-soft)] font-semibold text-[var(--primary)]":"text-[var(--muted)] hover:bg-slate-50 hover:text-[var(--foreground)]"}`}><Icon size={18}/><span>{label}</span>{active===label&&<ChevronRight size={15} className="ml-auto"/>}</Link>)}</nav><div className="absolute inset-x-4 bottom-5 rounded-2xl border border-[var(--border)] bg-[var(--panel-muted)] p-3"><div className="flex items-center gap-3"><div className="grid h-9 w-9 place-items-center rounded-full bg-slate-200 text-xs font-semibold text-slate-600">AD</div><div className="min-w-0"><p className="truncate text-sm font-semibold">Aathil Demo</p><p className="truncate text-xs capitalize text-[var(--muted)]">{role}</p></div><LogOut size={15} className="ml-auto text-[var(--muted)]"/></div></div></aside><header className="sticky top-0 z-30 flex h-16 items-center justify-between border-b border-[var(--border)] bg-white/90 px-4 backdrop-blur lg:ml-[248px] lg:px-8"><div className="flex items-center gap-3 lg:hidden"><Logo compact/><span className="text-sm font-semibold">Smart Assessment</span></div><div className="hidden text-sm text-[var(--muted)] lg:block">Good afternoon, <span className="font-semibold text-[var(--foreground)]">Aathil</span></div><div className="flex items-center gap-2"><button aria-label="Notifications" className="grid h-9 w-9 place-items-center rounded-xl border border-[var(--border)] bg-white text-[var(--muted)]">•</button><button className="flex h-9 items-center gap-2 rounded-xl border border-[var(--border)] bg-white px-3 text-sm font-medium"><span className="grid h-6 w-6 place-items-center rounded-full bg-slate-100 text-[10px] font-bold">AD</span><span className="hidden sm:block">Aathil</span></button><button aria-label="Open menu" className="grid h-9 w-9 place-items-center rounded-xl border border-[var(--border)] lg:hidden"><Menu size={17}/></button></div></header><main className="lg:ml-[248px]">{children}</main></div>;
}

export function PageHeader({ eyebrow,title,description,action }:{eyebrow?:string;title:string;description?:string;action?:ReactNode}){return <div className="flex flex-col gap-4 border-b border-[var(--border)] bg-white px-5 py-6 sm:px-8 lg:px-10 lg:py-7 xl:flex-row xl:items-end xl:justify-between"><div>{eyebrow&&<p className="mb-2 text-[11px] font-semibold uppercase tracking-[.15em] text-[var(--primary)]">{eyebrow}</p>}<h1 className="text-[26px] font-semibold tracking-[-.03em] text-[var(--foreground)] sm:text-[30px]">{title}</h1>{description&&<p className="mt-2 max-w-2xl text-sm leading-6 text-[var(--muted)]">{description}</p>}</div>{action&&<div className="shrink-0">{action}</div>}</div>}

export function Button({children,href,variant="primary",icon}:{children:ReactNode;href?:string;variant?:"primary"|"secondary"|"ghost";icon?:ReactNode}){const cls=`inline-flex h-10 items-center justify-center gap-2 rounded-xl px-4 text-sm font-semibold transition focus:outline-none focus:ring-2 focus:ring-[var(--primary)]/20 ${variant==="primary"?"bg-[var(--primary)] text-white hover:bg-[var(--primary-strong)]":variant==="secondary"?"border border-[var(--border)] bg-white text-[var(--foreground)] hover:bg-slate-50":"text-[var(--muted)] hover:bg-slate-100"}`;return href?<Link className={cls} href={href}>{icon}{children}</Link>:<button className={cls}>{icon}{children}</button>}
export function Card({children,className=""}:{children:ReactNode;className?:string}){return <section className={`rounded-2xl border border-[var(--border)] bg-white ${className}`}>{children}</section>}
export function Status({children,tone}:{children:ReactNode;tone:"success"|"warning"|"neutral"|"ai"|"error"}){const m={success:"bg-[var(--success-soft)] text-[var(--success)]",warning:"bg-[var(--warning-soft)] text-[var(--warning)]",neutral:"bg-slate-100 text-slate-600",ai:"bg-[var(--ai-soft)] text-[var(--ai)]",error:"bg-[var(--error-soft)] text-[var(--error)]"};return <span className={`inline-flex items-center gap-1.5 rounded-full px-2.5 py-1 text-[11px] font-semibold ${m[tone]}`}>{children}</span>}
export function Metric({label,value,detail,icon:Icon,trend}:{label:string;value:string;detail?:string;icon:any;trend?:string}){return <Card className="p-5"><div className="flex items-start justify-between"><div className="grid h-10 w-10 place-items-center rounded-xl bg-[var(--primary-soft)] text-[var(--primary)]"><Icon size={18}/></div>{trend&&<span className="text-xs font-semibold text-[var(--success)]">{trend}</span>}</div><p className="mt-5 text-xs font-medium text-[var(--muted)]">{label}</p><p className="mt-1 text-2xl font-semibold tracking-[-.03em]">{value}</p>{detail&&<p className="mt-1 text-xs text-[var(--muted-foreground)]">{detail}</p>}</Card>}
export function ProgressBar({value}:{value:number}){return <div className="h-2 overflow-hidden rounded-full bg-slate-100"><div className="h-full rounded-full bg-[var(--primary)] transition-all duration-700" style={{width:`${Math.max(0,Math.min(100,value))}%`}}/></div>}
export function AiCallout({title,children}:{title:string;children:ReactNode}){return <div className="rounded-2xl border border-[#ded5ff] bg-[var(--ai-soft)] p-5"><div className="flex items-start gap-3"><div className="grid h-9 w-9 shrink-0 place-items-center rounded-xl bg-white text-[var(--ai)]"><Sparkles size={17}/></div><div><p className="text-sm font-semibold">{title}</p><div className="mt-1 text-sm leading-6 text-[var(--muted)]">{children}</div></div></div></div>}
export function AssessmentRow({name,className,status,score,due}:{name:string;className:string;status:"Published"|"Draft"|"Closed"|"In progress";score?:string;due?:string}){const tone=status==="Published"?"success":status==="Draft"?"neutral":status==="In progress"?"warning":"neutral";return <div className="flex flex-col gap-3 border-t border-[var(--border)] px-5 py-4 sm:flex-row sm:items-center"><div className="min-w-0 flex-1"><p className="truncate text-sm font-semibold">{name}</p><p className="mt-1 text-xs text-[var(--muted)]">{className}{due?` · ${due}`:""}</p></div><Status tone={tone}>{status}</Status>{score&&<p className="w-20 text-right text-sm font-semibold">{score}</p>}<ChevronRight size={16} className="hidden text-[var(--muted-foreground)] sm:block"/></div>}
export const IconSet={Plus,ArrowRight};
