/* eslint-disable @typescript-eslint/no-explicit-any */
"use client";
import Link from "next/link";
import { useEffect, useState } from "react";
import { ArrowRight, BookOpen, CheckCircle2, Clock3, Plus, Sparkles } from "lucide-react";
import { AppShell, AiCallout, Card, PageHeader, ProgressBar, Status } from "@/app/components/ui";

export default function StudentPage() {
  const [assessments, setAssessments] = useState<any[]>([]);
  const [code, setCode] = useState("");
  const [message, setMessage] = useState("");
  useEffect(() => { fetch("/api/assessments").then((r) => r.json()).then((d) => setAssessments(d.assessments ?? [])).catch(() => setAssessments([])); }, []);
  async function join(e: React.FormEvent) { e.preventDefault(); setMessage(""); const r = await fetch("/api/classes/join", { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ code }) }); setMessage(r.ok ? "Class joined successfully." : (await r.json())?.error?.message ?? "Unable to join class."); }

  return <AppShell role="student" active="Dashboard">
    <PageHeader eyebrow="Student workspace" title="Keep learning moving" description="See what is due, continue assessments in progress, and focus on concepts that need another look." />
    <div className="mx-auto max-w-[1240px] space-y-6 px-5 py-6 sm:px-8 lg:px-10 lg:py-8">
      <div className="grid gap-4 sm:grid-cols-3"><Card className="p-5"><div className="flex items-center gap-3"><div className="grid h-9 w-9 place-items-center rounded-xl bg-[var(--primary-soft)] text-[var(--primary)]"><Clock3 size={17}/></div><div><p className="text-xs text-[var(--muted)]">To do</p><p className="text-2xl font-semibold">3</p></div></div></Card><Card className="p-5"><div className="flex items-center gap-3"><div className="grid h-9 w-9 place-items-center rounded-xl bg-[var(--warning-soft)] text-[var(--warning)]"><BookOpen size={17}/></div><div><p className="text-xs text-[var(--muted)]">In progress</p><p className="text-2xl font-semibold">1</p></div></div></Card><Card className="p-5"><div className="flex items-center gap-3"><div className="grid h-9 w-9 place-items-center rounded-xl bg-[var(--success-soft)] text-[var(--success)]"><CheckCircle2 size={17}/></div><div><p className="text-xs text-[var(--muted)]">Completed</p><p className="text-2xl font-semibold">8</p></div></div></Card></div>
      <div className="grid gap-6 xl:grid-cols-[1.45fr_1fr]">
        <Card className="overflow-hidden"><div className="flex items-center justify-between px-5 py-5"><div><h2 className="text-base font-semibold">Available assessments</h2><p className="mt-1 text-xs text-[var(--muted)]">Ready when you are.</p></div><Status tone="success">{assessments.length || 0} available</Status></div>{assessments.slice(0,5).map((item) => <Link key={item.id} href={`/student/assessments/${item.id}/take`} className="flex items-center gap-4 border-t border-[var(--border)] px-5 py-4 transition hover:bg-slate-50"><div className="grid h-10 w-10 shrink-0 place-items-center rounded-xl bg-[var(--primary-soft)] text-[var(--primary)]"><BookOpen size={17}/></div><div className="min-w-0 flex-1"><p className="truncate text-sm font-semibold">{item.title}</p><p className="mt-1 text-xs text-[var(--muted)]">{item.topic || "Assessment"}</p></div><ArrowRight size={16} className="text-[var(--muted)]"/></Link>)}{!assessments.length && <div className="p-8 text-center text-sm text-[var(--muted)]">No assessments available yet.</div>}</Card>
        <div className="space-y-6"><AiCallout title="Your learning focus">Practice <strong>Cell membrane transport</strong> next. Your recent answers suggest this concept could use a little more reinforcement.</AiCallout><Card className="p-5"><div className="flex items-center justify-between"><div><h2 className="text-sm font-semibold">Concept progress</h2><p className="mt-1 text-xs text-[var(--muted)]">Recent performance</p></div><Link href="/gaps" className="text-xs font-semibold text-[var(--primary)]">View gaps</Link></div><div className="mt-5 space-y-4"><div><div className="mb-2 flex justify-between text-xs"><span>Cell structure</span><b>88%</b></div><ProgressBar value={88}/></div><div><div className="mb-2 flex justify-between text-xs"><span>Genetics</span><b>74%</b></div><ProgressBar value={74}/></div><div><div className="mb-2 flex justify-between text-xs"><span>Membrane transport</span><b>52%</b></div><ProgressBar value={52}/></div></div></Card></div>
      </div>
      <Card className="p-5"><div className="flex flex-col gap-4 sm:flex-row sm:items-center"><div className="grid h-10 w-10 shrink-0 place-items-center rounded-xl bg-slate-100 text-slate-600"><Plus size={18}/></div><div className="flex-1"><h2 className="text-sm font-semibold">Join another class</h2><p className="mt-1 text-xs text-[var(--muted)]">Enter the code shared by your teacher.</p></div><form onSubmit={join} className="flex w-full gap-2 sm:w-auto"><input aria-label="Class code" value={code} onChange={(e)=>setCode(e.target.value)} placeholder="6-character code" className="h-10 w-full rounded-xl border border-[var(--border)] px-3 text-sm outline-none focus:border-[var(--primary)] sm:w-44"/><button className="h-10 rounded-xl bg-[var(--primary)] px-4 text-sm font-semibold text-white">Join</button></form></div>{message&&<p className="mt-3 text-xs text-[var(--muted)]">{message}</p>}</Card>
    </div>
  </AppShell>;
}
